config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/home'
  get 'dashboard/status'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :evaluations, only: [:new, :edit, :create, :update]
  resources :institutions, only: []
  resources :transcripts, only: [:new, :edit, :create, :update]
  resources :recommendations, only: [:show, :new, :edit, :create, :update]
  resources :submissions, only: [:index, :show, :new, :edit, :create, :update]

  devise_for :users

  get "/pages/*page" => "pages#show"

  root "pages#show", page: "index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def status
    if @submission = current_user.submission
      @radius = 90.0
      @percentage = 0

      @checklist = {
        :application => application_status,
        :recommendations => recommendations_status,
        :transcripts => transcripts_status,
        :approval => approval_status,
      }

      @offset = (100.0 - @percentage) / 100 * Math::PI * @radius * 2
    else
      redirect_to dashboard_home_path, :notice => "Please complete scholarship application first."
    end
  end

  private

  def increase_percentage_if(status)
    if status
      @percentage += 25
    end

    status
  end

  def application_status
    increase_percentage_if(@submission.present?)
  end

  def recommendations_status
    @required = @submission.reapply ? 2 : 3
    @recommendations = @submission.recommendations.
      where.not(:recommendation_updated_at => nil)
    increase_percentage_if(@recommendations.count >= @required)
  end

  def transcripts_status
    @institutions = Institution.select(:id).where(:submission => @submission.id)
    @transcripts = Transcript.where(:institution => [@institutions])
      .where.not(:upload_updated_at => nil)
    increase_percentage_if(@institutions.count == @transcripts.count)
  end

  def approval_status
    increase_percentage_if(@submission.approval)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_notice.html.erb
<p><%= notice %></p>

app/views/dashboard/_options-applicant.html.erb
<h1>So, what all do I need to do?</h1>
<p>Please complete each step below by clicking on each one. Your application must be completed before you will be able to request transcripts or recommendations. Check back for status updates to see how close you are too completing your application!</p>
<ul class="dashboard" id="welcome">
  <li>
    <%= link_to new_submission_path do %>
      <span class="orange">1. Submit scholarship application</span>
      <p>Fill out and submit the scholarship application online. The application must be submitted before you will be able to proceed to the other parts.<p>
      <p>Please note that all fields are required before the system will accept your application. Once successfully submitted, applications may be edited as many times as needed.</p>
      <p>To complete the application, you will need to have an Adobe PDF of your drivers license, resume, and a current catalog expense page(s) from your college or university.</p>
    <% end %>
  </li>
  <li>
    <%= link_to new_transcript_path do %>
      <span class="red">2. Request transcript(s)</span>
      <p>Once your application is submitted, you will need to submit a transcript for each higher education institution you've attended.</p>
    <% end %>
  </li>
  <li>
    <%= link_to new_recommendation_path do %>
      <span class="green">3. Request recommendations</span>
      <p>Once your application is submitted, you will need three recommendations. These are commonly from professors, employers, coworkers, and colleagues.</p>
    <% end %>
  </li>
  <li>
    <%= link_to dashboard_status_path do %>
      <span>4. Check for status updates</span>
      <p>Once your application is complete, be sure to check back on updates on being selected!</p>
    <% end %>
  </li>
</ul>

app/views/dashboard/_options-naja.html.erb
<h1>So, what options do I have?</h1>
<ul class="dashboard" id="welcome">
  <li>
    <%= link_to submissions_path do %>
      <span class="orange">View applicant submissions.</span>
      <p>You can view applicant submissions along with each of the attachmens.<p>
    <% end %>
  </li>
  <li>
    <%= link_to submissions_path do %>
      <span class="red">Grade applicant submissions.</span>
      <p>You can grade each applicant based on committee grading standards.</p>
    <% end %>
  </li>
  <li>
    <%= link_to submissions_path do %>
      <span class="green">View applicant scores.</span>
      <p>You can view the scores of the applicants.</p>
    <% end %>
  </li>
  <li>
    <%= link_to  do %>
      <span>You can view tailored reports.</span>
      <p>TBD</p>
    <% end %>
  </li>
</ul>

app/views/dashboard/_reapply.html.erb
<h1>Received a NAJA Scholarship before?</h1>

<p>Looking to reapply? The reapplication process is streamlined for returning applicants. Please remember to select the "Previously Awareded" checkbox at the top of the application.</p>
<p>Just like last year, please complete each step below by clicking on each one. Your application must be completed before you will be able to request transcripts or recommendations. Check back for status updates to see how close you are to completing your application!</p>

<ul class="dashboard">
  <li>
    <%= link_to new_submission_path, class: "white" do %>
      1. Submit scholarship application
      <p>Fill out and submit the scholarship application online. The application must be submitted before you will be able to proceed to the other parts.<p>
    <% end %>
  </li>
  <li>
    <%= link_to new_transcript_path, class: "white" do %>
      2. Request transcript(s)
      <p>Once your application is submitted, you will need to submit your most recent transcript since receiving a NAJA scholarship.</p>
    <% end %>
  </li>
  <li>
    <%= link_to new_recommendation_path, class: "white" do %>
      3. Request recommendation
      <p>Once your application is submitted, you will need two recommendations. These are commonly from professors, employers, coworkers, and colleagues.</p>
    <% end %>
  </li>
  <li>
    <%= link_to dashboard_status_path, class: "white" do %>
      4. Check for status updates
      <p>Once your application is complete, be sure to check back on updates on being selected!</p>
    <% end %>
  </li>
</ul>

app/views/dashboard/_status-welcome.html.erb
<h1>Want to check your application status?</h1>

<div id="gauge" data-pct="<%= @percentage %>">
  <svg id="svg" width="200" height="200" viewPort="0 0 100 100" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <circle r="<%= @radius %>" cx="100" cy="100" fill="transparent" stroke-dasharray="565.48"
      stroke-dashoffset="0"></circle>
    <circle id="bar" r="90" cx="100" cy="100" fill="transparent" stroke-dasharray="565.48"
      style="stroke-dashoffset: <%= @offset %>;"></circle>
  </svg>
</div>

app/views/dashboard/_status.html.erb
<h1>Application checklist</h1>

<ul class="application-checklist">
  <li>
    <% if @checklist[:application] %>
      <span class="green">Application is submitted.</span>
    <% else %>
      <span class="red">Application is not submitted.</span>
    <% end %>
  </li>
  <li>
    <% if @checklist[:transcripts] %>
      <span class="green">Transcript(s) have been received.</span>
      <p><%= "#{@transcripts.count} of #{@institutions.count}"%> transcripts have been received.</p>
    <% else %>
      <span class="red">Transcript(s) have not been received.</span>
      <p><%= "#{@transcripts.count} of #{@institutions.count}"%> transcripts have been received.</p>
    <% end %>
  </li>
  <li>
    <% if @checklist[:recommendations] %>
      <span class="green">Recommendations have been received.</span>
      <p><%= @recommendations.count %> of <%= @required %> recommendations have been received.</p>
    <% else %>
      <span class="red">Recommendations have not been received.</span>
      <p><%= @recommendations.count %> of <%= @required %> recommendations have been received.</p>
    <% end %>
  </li>
  <li>
    <% if @checklist[:approval] %>
      <span class="green">Application is approved.</span>
    <% else %>
      <span class="red">Application is not approved.</span>
      <p>Once all parts of your application have been received, your application will go to NAJA for approval.</p>
    <% end %>
  </li>
</ul>

app/views/dashboard/_welcome-applicant.html.erb
<h1>Welcome to the application portal.</h1>
<p>This is your candidate portal and one-stop-shop for submitting and checking back on the status of your NAJA scholarship application. As you complete the parts of the application, the dashboard to the left will start to fill up. When it's full, NAJA has received your application!</p>
<a href="/pages/about"><button>Make sure you qualify</button></a>

app/views/dashboard/_welcome-naja.html.erb
<h1>Welcome to the committee side.</h1>
<p>This is your committee portal and one-stop-shop for viewing and grading applicant submissions.</p>

app/views/dashboard/home.html.erb
<div class="splash-header">
  <div class="splash-header-secondary">
    <div>
      <%= render 'notice' %>
    </div>
  </div>
  <div class="splash-header-primary">
    <div>
      <% if current_user.admin? %>
        <%= render 'welcome-naja' %>
      <% else %>
        <%= render 'welcome-applicant' %>
      <% end %>
    </div>
  </div>
</div>
<div class="splash-content">
  <div class="splash-content-secondary"></div>
  <div class="splash-content-primary">
    <div>
      <% if current_user.admin? %>
        <%= render 'options-naja' %>
      <% else %>
        <%= render 'options-applicant' %>
      <% end %>
    </div>
  </div>
</div>
<% unless current_user.admin? %>
  <div class="splash-reapply">
    <div class="content">
      <%= render 'reapply' %>
    </div>
  </div>
<% end %>

app/views/dashboard/status.html.erb
<div class="splash-header">
  <div class="splash-header-secondary">
    <div>
      <%= render 'notice' %>
    </div>
  </div>
  <div class="splash-header-primary">
    <div>
      <%= render 'status-welcome' %>
    </div>
  </div>
</div>
<div class="splash-content">
  <div class="splash-content-secondary"></div>
  <div class="splash-content-primary">
    <div>
      <%= render 'status' %>
    </div>
  </div>
</div>