config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/home'
  get 'dashboard/status'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :evaluations, only: [:new, :edit, :create, :update]
  resources :institutions, only: []
  resources :transcripts, only: [:new, :edit, :create, :update]
  resources :recommendations, only: [:show, :new, :edit, :create, :update]
  resources :submissions, only: [:index, :show, :new, :edit, :create, :update]

  devise_for :users

  get "/pages/*page" => "pages#show"

  root "pages#show", page: "index"
end

app/models/transcript.rb
class Transcript < ApplicationRecord
  belongs_to :institution

  has_attached_file :upload

  has_secure_token

  validates_attachment :upload, content_type: { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/transcripts_controller.rb
class TranscriptsController < ApplicationController
  before_action :authenticate_user!, except: [:edit, :update]
  before_action :is_active?
  before_action :set_transcript, only: [:show, :edit, :update, :destroy]

  # GET /transcripts
  # GET /transcripts.json
  def index
  end

  # GET /transcripts/1
  # GET /transcripts/1.json
  def show
  end

  # GET /transcripts/new
  def new
    if current_user.submission
      @transcript = Transcript.new
      @submission = Submission.find_by_user_id(current_user.id)
      @transcripts = Transcript.where(:institution => [@submission.institutions.pluck(:id)])
    else
      redirect_to dashboard_home_path, :notice => "Please complete scholarship application first."
    end
  end

  # GET /transcripts/1/edit
  def edit
    unless params[:token] == @transcript.token
      redirect_to root_path
    end

    @submission = @transcript.institution.submission
  end

  # POST /transcripts
  # POST /transcripts.json
  def create
    @transcript = Transcript.new(transcript_params)

    respond_to do |format|
      if @transcript.save
        TranscriptRequestMailer.transcript_request(@transcript).deliver
        format.html { redirect_to dashboard_home_path, notice: 'Transcript was successfully created.' }
        format.json { render :show, status: :ok, location: @transcript }
      else
        format.html { render :new }
        format.json { render json: @transcript.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transcripts/1
  # PATCH/PUT /transcripts/1.json
  def update
    @submission = @transcript.institution.submission

    respond_to do |format|
      if @transcript.update(transcript_params)
        TranscriptMailer.transcript_confirmation(@transcript).deliver
        format.html { redirect_to root_url, notice: 'Transcript was successfully updated.' }
        format.json { render :show, status: :ok, location: @transcript }
      else
        format.html { render :edit }
        format.json { render json: @transcript.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transcripts/1
  # DELETE /transcripts/1.json
  def destroy
    @transcript.destroy
    respond_to do |format|
      format.html { redirect_to transcripts_url, notice: 'Transcript was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def is_active?
      if !Setting.first.active
        redirect_to dashboard_home_path, :notice => "Sorry, applications are currently closed. Applications are open between September and February."
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transcript
      @transcript = Transcript.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transcript_params
      params.require(:transcript).permit(:institution_id, :upload, :email, :submission)
    end
end

app/helpers/transcripts_helper.rb
module TranscriptsHelper
end

app/views/transcripts/_edit.html.erb
<%= form_for @transcript do |form| %>
  <% if transcript.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transcript.errors.count, "error") %> prohibited this transcript from being saved:</h2>

      <ul>
        <% transcript.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><span>Applicant</span>: <%= @submission.name %></p>
    <p><span>Institution</span>: <%= @transcript.institution.name %></p>
    <p>The applicant has been asked to secure official transcripts from previously attended institutions.</p>
    <p>Please use the form below to upload a PDF of the applicant's official trascript.</p>
    <%= form.file_field :upload %>
    <% if @transcript.upload.present? %>
      <p><%= link_to 'View transcript', @transcript.upload.url %></p>
    <% end %>
    <input type="submit" name="commit" value="Submit transcript" data-disable-with="Submit transcript">
  </div>
<% end %>

app/views/transcripts/_form.html.erb
<%= form_for @transcript, url: transcripts_path, html: { multipart: true } do |form| %>
  <% if transcript.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transcript.errors.count, "error") %> prohibited this transcript from being saved:</h2>

      <ul>
      <% transcript.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions transcript-create">
    <div>
      <%= form.select :institution_id, options_for_select(
      Institution.where(:submission_id => @submission.id)
        .map{|institution| [institution.name, institution.id]}
      ) %>
    </div>
    <div>
      <%= form.text_field :email, placeholder: 'Email address', :autofocus => true %>
    </div>
    <div><%= form.submit 'Request transcript' %></div>
  </div>
<% end %>

<h2 class="transcripts-previously-submitted">Previously Submitted Transcripts</h2>

<ul>
<% @transcripts.each do |transcript| %>
  <li>
    <%= link_to transcript.institution.name, transcript.upload.url %>
  </li>
<% end %>
</ul>

app/views/transcripts/edit.html.erb
<div class="main">
  <h1>Submit Official Transcript</h1>
  <div>
    <%= render 'edit', transcript: @transcript %>
  </div>
</div>

app/views/transcripts/index.html.erb
<div class="main">
  <h1>Transcripts</h1>
  <div>
    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transcripts.each do |transcript| %>
          <tr>
            <td><%= link_to transcript.institution.name, transcript.upload.url %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/transcripts/new.html.erb
<div class="main">
  <h1>New Transcript</h1>
  <div>
    <p>Official transcripts are required for all undergraduate and graduate studies completed by the applicant from each school previously attended as well as the school you are currently attending. Include community colleges or universities attended during your bachelor, masters, or doctorate programs.</p>
    <p>Contact the Office of Student Records and Registrar to pay any transcript fees and obtain an official email address before completing the form below to request an official transcript. You may use this form multiple times to request multiple transcripts. An email invitation containing a link will be emailed to the college or university requesting that your transcript be uploaded on your behalf.</p>
    <p>If your college or university is unable to upload your transcript, an official electronic transcript may be emailed directly to NAJA at <%= mail_to 'mlee@najanet.org', 'mlee@najanet.org' %> or mailed to NAJA 845 S Main Street, Greenville, MS, 38701.</p>
    <p>Unofficial transcripts uploaded by students will not be accepted.</p>
    <%= render 'form', transcript: @transcript %>
  </diV>
</div>

app/views/transcripts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transcript_path(@transcript) %> |
<%= link_to 'Back', transcripts_path %>