config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/home'
  get 'dashboard/status'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :evaluations, only: [:new, :edit, :create, :update]
  resources :institutions, only: []
  resources :transcripts, only: [:new, :edit, :create, :update]
  resources :recommendations, only: [:show, :new, :edit, :create, :update]
  resources :submissions, only: [:index, :show, :new, :edit, :create, :update]

  devise_for :users

  get "/pages/*page" => "pages#show"

  root "pages#show", page: "index"
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :submission

  has_attached_file :recommendation

  has_secure_token

  validates :email, :presence => true, :on => :create
  validates :recommendation, :presence => true, :on => :update

  validates_attachment :recommendation, content_type: { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :authenticate_user!, except: [:edit, :update]
  before_action :is_active?, except: [:show]
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    if !current_user.admin
      redirect_to root_path
    end
    @submission = @recommendation.submission
  end

  # GET /recommendations/new
  def new
    if current_user.submission
      @recommendation = Recommendation.new
    else
      redirect_to dashboard_home_path, :notice => "Please complete scholarship application first."
    end
  end

  # GET /recommendations/1/edit
  def edit
    unless params[:token] == @recommendation.token
      redirect_to root_path
    end
    @submission = @recommendation.submission
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)
    @submission = Submission.find_by_user_id(current_user.id)
    @recommendation.submission_id = @submission.id

    respond_to do |format|
      if @recommendation.save
        RecommendationRequestMailer.recommendation_request(@recommendation).deliver
        format.html { redirect_to dashboard_home_path, notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    @submission = @recommendation.submission

    respond_to do |format|
      if @recommendation.update(recommendation_params)
        RecommendationMailer.recommendation_confirmation(@recommendation).deliver
        format.html { redirect_to root_url, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def is_active?
      if !Setting.first.active
        redirect_to dashboard_home_path, :notice => "Sorry, applications are currently closed. Applications are open between September and February."
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(
        :address,
        :email,
        :capacity,
        :communication,
        :department,
        :habits,
        :institution,
        :maturity,
        :motivation,
        :name,
        :personality,
        :rating,
        :recommendation,
        :responsibility,
        :title,
        :years,
      )
    end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_edit-disabled.html.erb
<%= form_for @recommendation do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
        <% recommendation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><span>Applicant</span>: <%= @submission.name %></p>
    <p><span>Proposed field of study</span>: <%= @submission.field.name %></p>
    <p>The applicant has been asked to secure evaluations from instructors, employers, and/or others who know him/her and his/her capabilities.</p>
    <p>Use the comments section to refer to the applicant's strong and weak points. This is most useful to the National Scholarship Committee when making its decision. Since the purpose of the NAJA Scholarship is to help graduate students who will work DIRECTLY with children with special and particular needs, please comment on this applicant's goals in this respect.</p>
    <div class="clearfix">
      <div class="overview">
        <h2>Your information and overview</h2>
        <%= form.text_field :name, placeholder: 'Name', :autofocus => true %>
        <%= form.text_field :title, placeholder: 'Title' %>
        <%= form.text_field :department, placeholder: 'Department' %>
        <%= form.text_field :institution, placeholder: 'Institution' %>
        <%= form.text_field :address, placeholder: 'Address' %>
        How long have you known the applicant? 
        <%= form.number_field :years, placeholder: 'number of years' %>
        In what capacity have you known the application? 
        <%= form.text_field :capacity, placeholder: 'capacity' %>
        <div>
          Recommendation rating:
          <%= form.select :rating, options_for_select(
            Rating.all.map{|rating| [rating.name, rating.id]}
          ) %>
        </div>
      </div>
      <div class="impressions">
        <h2>General Impressions</h2>
        <div class="clearfix">
          <p>Ability to communication with others: </p>
          <%= form.select :communication, options_for_select(
            Impression.all.map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Motivation to work with special needs children: </p>
          <%= form.select :motivation, options_for_select(
            Impression.all.map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Work habits: </p>
          <%= form.select :habits, options_for_select(
            Impression.all.map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Sense of responsibility and reliability: </p>
          <%= form.select :responsibility, options_for_select(
            Impression.all.map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Personality: </p>
          <%= form.select :personality, options_for_select(
            Impression.all.map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Poise, emotional stability, and maturity: </p>
          <%= form.select :maturity, options_for_select(
            Impression.all.map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
      </div>
      <div class="recommendation">
        <%= link_to 'Written Recommendation', @recommendation.recommendation.url %>
      </div>
    </div>
  </div>
<% end %>

app/views/recommendations/_edit.html.erb
<%= form_for @recommendation do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
        <% recommendation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><span>Applicant</span>: <%= @submission.name %></p>
    <p><span>Proposed field of study</span>: <%= @submission.field.name %></p>
    <p>The applicant has been asked to secure evaluations from instructors, employers, and/or others who know him/her and his/her capabilities.</p>
    <p>Use the comments section to refer to the applicant's strong and weak points. This is most useful to the National Scholarship Committee when making its decision. Since the purpose of the NAJA Scholarship is to help graduate students who will work DIRECTLY with children with special and particular needs, please comment on this applicant's goals in this respect.</p>
    <div class="clearfix">
      <div class="overview">
        <h2>Your information and overview</h2>
        <%= form.text_field :name, placeholder: 'Name', :autofocus => true %>
        <%= form.text_field :title, placeholder: 'Title' %>
        <%= form.text_field :department, placeholder: 'Department' %>
        <%= form.text_field :institution, placeholder: 'Institution' %>
        <%= form.text_field :address, placeholder: 'Address' %>
        How long have you known the applicant? 
        <%= form.number_field :years, placeholder: 'number of years' %>
        In what capacity have you known the application? 
        <%= form.text_field :capacity, placeholder: 'capacity' %>
        <div>
          Recommendation rating:
          <%= form.select :rating, options_for_select(
            Rating.order(id: :desc).map{|rating| [rating.name, rating.id]}
          ) %>
        </div>
      </div>
      <div class="impressions">
        <h2>General Impressions</h2>
        <div class="clearfix">
          <p>Ability to communication with others: </p>
          <%= form.select :communication, options_for_select(
            Impression.order(id: :desc).map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Motivation to work with special needs children: </p>
          <%= form.select :motivation, options_for_select(
            Impression.order(id: :desc).map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Work habits: </p>
          <%= form.select :habits, options_for_select(
            Impression.order(id: :desc).map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Sense of responsibility and reliability: </p>
          <%= form.select :responsibility, options_for_select(
            Impression.order(id: :desc).map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Personality: </p>
          <%= form.select :personality, options_for_select(
            Impression.order(id: :desc).map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
        <div class="clearfix">
          <p>Poise, emotional stability, and maturity: </p>
          <%= form.select :maturity, options_for_select(
            Impression.order(id: :desc).map{|impression| [impression.name, impression.id]}
          ) %>
        </div>
      </div>
      <div class="recommendation">
        <h2>Written Recommendation</h2>
        <p>A letter of recommendation must be attached. If not, the recommendation will be considered incomplete.</p>
        <%= form.file_field :recommendation %>
      </div>
    </div>
    <input type="submit" name="commit" value="Submit recommendation" data-disable-with="Submit recommendation">
  </div>
<% end %>

app/views/recommendations/_form-disabled.html.erb
<%= form_for @recommendation do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :email, placeholder: 'Email address', :autofocus => true %>
  </div>
<% end %>

app/views/recommendations/_form.html.erb
<%= form_for @recommendation do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :email, placeholder: 'Email address', :autofocus => true %>
    <%= form.submit 'Request recommendation' %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<div class="main">
  <h1>Submit Recommendation</h1>
  <div>
    <%= render 'edit', recommendation: @recommendation %>
  </div>
</div>

app/views/recommendations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommendations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<div class="main">
  <h1>New Recommendation</h1>
  <div>
    <p>Please enter an email address below to request a recommendation. You may use this form multiple times to request multiple recommendations.</p>
    <p>First time applicants are required to submit at least three (3) recommendations. Returning applicants are required to submit at least two (2) recommendations.</p>
    <p>Two of the recommendations must be professional recommendations from educators, professors, employers or individuals who know the applicant and are in the field of work or studies that the applicant is pursuing.</p>
    <p>One recommendation must be from an individual (non-relative) who has known the applicant long enough to make comments on character, abilities, motivation, background etc. of the applicant.</p>
    <%= render 'form', recommendation: @recommendation %>
  </div>
</div>

app/views/recommendations/show.html.erb
<div class="main">
  <h1>Show Applicant Recommendation</h1>

  <div class="recommendations">
    <p id="notice"><%= notice %></p>

    <p>Please note that any changes made to this form will not be saved.</p>

    <div class="recommendations-form">
      <%= render 'edit-disabled', recommendation: @recommendation %>
    </div>
  </div>
</div>