config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/home'
  get 'dashboard/status'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :evaluations, only: [:new, :edit, :create, :update]
  resources :institutions, only: []
  resources :transcripts, only: [:new, :edit, :create, :update]
  resources :recommendations, only: [:show, :new, :edit, :create, :update]
  resources :submissions, only: [:index, :show, :new, :edit, :create, :update]

  devise_for :users

  get "/pages/*page" => "pages#show"

  root "pages#show", page: "index"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user

  has_attached_file :expense
  has_attached_file :license
  has_attached_file :resume

  has_many :employments
  has_many :evaluations
  has_many :honors
  has_many :institutions
  has_many :recommendations
  has_many :relatives
  has_many :volunteers

  accepts_nested_attributes_for :employments, :allow_destroy => true
  accepts_nested_attributes_for :relatives, :allow_destroy => true
  accepts_nested_attributes_for :institutions, :allow_destroy => true
  accepts_nested_attributes_for :honors, :allow_destroy => true
  accepts_nested_attributes_for :volunteers, :allow_destroy => true

  validates_attachment :expense, content_type: { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  validates_attachment :license, content_type: { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  validates_attachment :resume, content_type: { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  validates :year, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :permanent_address, :presence => true
  validates :permanent_city, :presence => true
  validates :permanent_state, :presence => true
  validates :permanent_zip, :presence => true
  validates :permanent_phone, :presence => true
  validates :citizen, :presence => true
  validates :field_id, :presence => true
  validates :degree_id, :presence => true
  validates :institution_name, :presence => true
  validates :institution_city, :presence => true
  validates :institution_state, :presence => true
  validates :graduation_month, :presence => true
  validates :graduation_year, :presence => true
  validates :summer_tuition, :presence => true
  validates :summer_books, :presence => true
  validates :summer_board, :presence => true
  validates :summer_other, :presence => true
  validates :summer_hours, :presence => true
  validates :fall_tuition, :presence => true
  validates :fall_books, :presence => true
  validates :fall_board, :presence => true
  validates :fall_other, :presence => true
  validates :fall_hours, :presence => true
  validates :winter_tuition, :presence => true
  validates :winter_books, :presence => true
  validates :winter_board, :presence => true
  validates :winter_other, :presence => true
  validates :winter_hours, :presence => true
  validates :spring_tuition, :presence => true
  validates :spring_books, :presence => true
  validates :spring_board, :presence => true
  validates :spring_other, :presence => true
  validates :spring_hours, :presence => true
  validates :state_id, :presence => true
  validates :frequency, :presence => true
  validates :motivation, :presence => true, :unless => :reapply?
  validates :license, attachment_presence: true, :unless => :reapply?
  validates :resume, attachment_presence: true
  validates :expense, attachment_presence: true

  def field
    Field.find(field_id)
  end

  def name
    "#{first_name} #{last_name}"
  end

  def overall
    commitment_average + scholarship_average + recommendations_average + goals_average
  end

  def score(user)
    evaluation = Evaluation.find_by(:submission => id, :user => user)

    evaluation ? evaluation.score : 0
  end

  private

  def commitment_average
    sum = Evaluation.select('sum(commitment) as sum, count(*) as count')
      .where(:submission_id => id)
    sum.exists? ? sum[0]['sum'] / sum[0]['count'].to_f : 0
  end

  def goals_average
    sum = Evaluation.select('sum(goals) as sum, count(*) as count')
      .where(:submission_id => id)
    sum[0]['sum'] ? sum[0]['sum'] / sum[0]['count'].to_f : 0
  end

  def recommendations_average
    sum = Evaluation.select('sum(recommendations) as sum, count(*) as count')
      .where(:submission_id => id)
    sum[0]['sum'] ? sum[0]['sum'] / sum[0]['count'].to_f : 0
  end

  def scholarship_average
    sum = Evaluation.select('sum(scholarship) as sum, count(*) as count')
      .where(:submission_id => id)
    sum[0]['sum'] ?  sum[0]['sum'] / sum[0]['count'].to_f : 0
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_active?, except: [:index, :show]
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    if !current_user.admin
      redirect_to root_path
    end

    @submissions = Submission.where(
      :approval => true,
      :year => Setting.year,
    ).order(:last_name)
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    if !current_user.admin
      redirect_to root_path
    end
  end

  # GET /submissions/new
  def new
    if current_user.submission
      redirect_to action: "edit", id: current_user.submission.id
    end

    @submission = Submission.new
    @submission.relatives.build
    4.times do
      @submission.honors.build
    end
    4.times do
      @submission.volunteers.build
    end
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.create
    @submission.attributes = submission_params
    @submission.user_id = current_user.id if current_user
    @submission.year = Setting.year

    respond_to do |format|
      if @submission.save
        SubmissionMailer.submission_confirmation(@submission).deliver
        format.html { redirect_to dashboard_home_path, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        SubmissionMailer.submission_confirmation(@submission).deliver
        format.html { redirect_to dashboard_home_path, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def is_active?
      if !Setting.first.active
        redirect_to dashboard_home_path, :notice => "Sorry, applications are currently closed. Applications are open between September and February."
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(
        :acceptance,
        :citizen,
        :current_address,
        :current_city,
        :current_phone,
        :current_state,
        :current_zip,
        :degree_id,
        :degree_explanation,
        :expense,
        :fall_board,
        :fall_books,
        :fall_hours,
        :fall_other,
        :fall_tuition,
        :field_explanation,
        :field_id,
        :first_name,
        :frequency,
        :graduation_month,
        :graduation_year,
        :institution_city,
        :institution_name,
        :institution_state,
        :last_name,
        :last_year,
        :last_year_explanation,
        :license,
        :maiden_name,
        :middle_name,
        :motivation,
        :permanent_address,
        :permanent_city,
        :permanent_phone,
        :permanent_state,
        :permanent_zip,
        :reapply,
        :resume,
        :spring_board,
        :spring_books,
        :spring_hours,
        :spring_other,
        :spring_tuition,
        :state_id,
        :studies_month,
        :studies_year,
        :summer_board,
        :summer_books,
        :summer_hours,
        :summer_other,
        :summer_tuition,
        :winter_board,
        :winter_books,
        :winter_hours,
        :winter_other,
        :winter_tuition,
        :year,
        employments_attributes:[
          :employer,
          :title,
          :start_month,
          :start_year,
          :end_month,
          :end_year,
          :_destroy,
          :id,
        ],
        honors_attributes:[
          :name,
          :_destroy,
          :id,
        ],
        institutions_attributes:[
          :name,
          :institution_start_month,
          :institution_start_year,
          :institution_end_month,
          :institution_end_year,
          :degree,
          :gpa,
          :_destroy,
          :id,
        ],
        relatives_attributes:[
          :name,
          :relationship,
          :address,
          :city,
          :state,
          :zip,
          :_destroy,
          :id,
        ],
        volunteers_attributes:[
          :name,
          :_destroy,
          :id,
        ],
      )
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def name(submission)
    "#{submission.last_name}, #{submission.first_name}"
  end

  def previous_submission(submission)
    previous_year = Setting.year - 1

    Submission.find_by(:user => submission.user, :year => previous_year)
  end
end

app/views/submissions/_employment.html.erb
<div>
  <%= form.add_nested_fields_link :employments, 'Add employment' %>
  <%= form.nested_fields_for :employments do |employment| %>
    <div>
      <%= employment.text_field :employer, placeholder: 'Employer' %>
    </div>
    <div>
      <%= employment.text_field :title, placeholder: 'Job title' %>
    </div>
    <div>
      <%= employment.label :start, 'From date:' %>
      <%= employment.number_field :start_month, :placeholder => 'Starting month', :required => true %>
      <%= employment.number_field :start_year , :placeholder => 'Starting year', :required => true %>
    </div>
    <div>
      <%= employment.label :end, 'To date:' %>
      <%= employment.number_field :end_month, :placeholder => 'Ending month', :required => true %>
      <%= employment.number_field :end_year, :placeholder => 'Ending year', :required => true %>
    </div>
  <% end %>
</div>

app/views/submissions/_form-disabled.html.erb
<%= form_for @submission do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2 class="error"><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="personal-information">
      <p class="reapply">
        <%= form.check_box :reapply %>
        <%= form.label :reapply, 'This is a repplication.' %>
      </p>
      <h2>Personal information</h2>
      <div>
        <h3>Name</h3>
        <%= form.text_field :first_name, :class => field_class(@submission, :first_name), placeholder: 'First name', :autofocus => true %>
        <%= form.text_field :middle_name, :class => field_class(@submission, :middle_name), placeholder: 'Middle name' %>
        <%= form.text_field :last_name, :class => field_class(@submission, :last_name), placeholder: 'Last name' %>
        <%= form.label :citizen, 'I am a U.S. citizen.', :class => field_class(@submission, :citizen) %>
        <%= form.check_box :citizen %>
        <div class="not-required-on-reapply">
          <p class="<%= field_class(@submission, :license) %>">Adobe PDF of your driver's license:</p>
          <%= form.file_field :license %>
          <% if @submission.license.present? %>
            <%= link_to 'View license', @submission.license.url %>
          <% end %>
        </div>
      </div>
      <div>
        <h3>Permanent address</h3>
        <%= form.text_field :permanent_address, :class => field_class(@submission, :permanent_address), placeholder: 'Permanent address' %>
        <%= form.text_field :permanent_city, :class => field_class(@submission, :permanent_city), placeholder: 'Permanent city' %>
        <%= form.text_field :permanent_state, :class => field_class(@submission, :permanent_state), placeholder: 'Permanent state' %>
        <%= form.text_field :permanent_zip, :class => field_class(@submission, :permanent_zip), placeholder: 'Permanent zip' %>
        <%= form.phone_field :permanent_phone, :class => field_class(@submission, :permanent_phone), placeholder: 'Permanent phone number' %>
      </div>
      <div>
        <h3>Current address <span>(if different)</span></h3>
        <%= form.text_field :current_address, placeholder: 'Current address' %>
        <%= form.text_field :current_city, placeholder: 'Current city' %>
        <%= form.text_field :current_state, placeholder: 'Current state' %>
        <%= form.text_field :current_zip, placeholder: 'Current zip' %>
        <%= form.phone_field :current_phone, placeholder: 'Current phone number' %>
      </div>
    </div>
    <div class="relative">
      <h2>Nearest relative</h2>
      <%= render :partial => 'relative', :locals => {:form => form} %>
    </div>
    <div class="not-required-on-reapply">
      <div class="employments">
        <h2>Employment history</h2>
        <%= render :partial => 'employment', :locals => {:form => form} %>
        <div>
          <p class="<%= field_class(@submission, :resume)  %>">Adobe PDF of your resume:</p>
          <%= form.file_field :resume %>
          <% if @submission.resume.present? %>
            <%= link_to 'View resume', @submission.resume.url %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="institutions">
      <h2>Institutions attended</h2>
      <%= render :partial => 'institutions', :locals => {:form => form} %>
    </div>
    <div class="not-required-on-reapply">
      <div class="honors">
        <h2>Honors, scholarships, or special recognitions</h2>
        <p>At least 4 are required.</p>
        <%= render :partial => 'honors', :locals => {:form => form} %>
      </div>
      <div class="volunteers">
        <h2>Civic or cultural involvements and volunteerisms</h2>
        <p>At least 4 are required.</p>
        <%= render :partial => 'volunteers', :locals => {:form => form} %>
      </div>
    </div>
    <div class="anticipated-institution-information clearfix">
      <h2>Future education information</h2>
      <div>
        <h3>Institution</h3>
        <%= form.text_field :institution_name, :class => field_class(@submission, :institution_name), placeholder: 'Institution name' %>
        <%= form.text_field :institution_city, :class => field_class(@submission, :institution_city), placeholder: 'Institution city' %>
        <%= form.text_field :institution_state, :class => field_class(@submission, :institution_state), placeholder: 'Institution state' %>
      </div>
      <div class="institution-information">
        <h3>Enrollment</h3>
        <div>
          <%= form.label :accepted, 'Have you been accepted into this graduate program?', :class => field_class(@submission, :acceptance) %>
          <%= form.radio_button :acceptance, true %> Yes
          <%= form.radio_button :acceptance, false %> No
        </div>
        <div>
          <div>
            <%= form.label :start_date, 'Date your studies will begin:', :class => field_class(@submission, :start_date) %>
          </div>
          <div class="right">
            <%= form.number_field :studies_month, :placeholder => 'Month', :required => true %>
            <%= form.number_field :studies_year, :placeholder => 'Year', :required => true %>
          </div>
        </div>
        <div>
          <div>
            <%= form.label :last_year, 'Will you earn your degree this year?', :class => field_class(@submission, :last_year) %>
            <%= form.radio_button :last_year, true %> Yes
            <%= form.radio_button :last_year, false %> No
          </div>
        </div>
        <div>
          <div>
            <%= form.label :start_date, 'Date that you will earn your degree:', :class => field_class(@submission, :start_date) %>
          </div>
          <div class="right">
            <%= form.number_field :graduation_month, :placeholder => 'Month', :required => true %>
            <%= form.number_field :graduation_year, :placeholder => 'Year', :required => true %>
          </div>
        </div>
        <div>
          <%= form.text_field :last_year_explanation, placeholder: 'If not, explain.' %>
        </div>
      </div>
      <div>
        <h3>Program</h3>
        <div>
          <%= form.label :field_id, 'Proposed field of study:', :class => field_class(@submission, :field_id) %>
          <%= form.select :field_id, options_for_select(
            Field.all.map{|field| [field.name, field.id]},
            @submission.field_id
          ) %>
        </div>
        <div>
          <%= form.text_field :field_explanation, placeholder: 'If other, explain.' %>
        </div>
        <div>
          <%= form.label :degree_id, 'Degree you will work to obtain:', :class => field_class(@submission, :degree_id) %>
          <%= form.select :degree_id, options_for_select(
            Degree.all.map{|degree| [degree.name, degree.id]},
            @submission.degree_id
          ) %>
        </div>
        <div>
          <%= form.text_field :degree_explanation, placeholder: 'If other, explain.' %>
        </div>
      </div>
      <div class="cost-estimates">
        <h3>Cost estimates (round to nearest whole dollar)</h3>
        <div>
          <div>
            <%= form.number_field :summer_tuition, :class => field_class(@submission, :summer_tuition), placeholder: 'Summer tuition/fees' %>
            <%= form.number_field :summer_books, :class => field_class(@submission, :summer_books), placeholder: 'Summer books' %>
            <%= form.number_field :summer_board, :class => field_class(@submission, :summer_board), placeholder: 'Summer room/board' %>
            <%= form.number_field :summer_other, :class => field_class(@submission, :summer_other), placeholder: 'Summer other' %>
            <%= form.number_field :summer_hours, :class => field_class(@submission, :summer_hours), placeholder: 'Summer hours' %>
          </div>
          <div>
            <%= form.number_field :fall_tuition, :class => field_class(@submission, :fall_tuition), placeholder: 'Fall tuition/fees' %>
            <%= form.number_field :fall_books, :class => field_class(@submission, :fall_books), placeholder: 'Fall books' %>
            <%= form.number_field :fall_board, :class => field_class(@submission, :fall_board), placeholder: 'Fall room/board' %>
            <%= form.number_field :fall_other, :class => field_class(@submission, :fall_other), placeholder: 'Fall other' %>
            <%= form.number_field :fall_hours, :class => field_class(@submission, :fall_hours), placeholder: 'Fall hours' %>
          </div>
        </div>
        <div>
          <div>
            <%= form.number_field :winter_tuition, :class => field_class(@submission, :winter_tuition), placeholder: 'Winter tuition/fees' %>
            <%= form.number_field :winter_books, :class => field_class(@submission, :winter_books), placeholder: 'Winter books' %>
            <%= form.number_field :winter_board, :class => field_class(@submission, :winter_board), placeholder: 'Winter room/board' %>
            <%= form.number_field :winter_other, :class => field_class(@submission, :winter_other), placeholder: 'Winter other' %>
            <%= form.number_field :winter_hours, :class => field_class(@submission, :winter_hours), placeholder: 'Winter hours' %>
          </div>
          <div>
            <%= form.number_field :spring_tuition, :class => field_class(@submission, :spring_tuition), placeholder: 'Spring tuition/fees' %>
            <%= form.number_field :spring_books, :class => field_class(@submission, :spring_books), placeholder: 'Spring books' %>
            <%= form.number_field :spring_board, :class => field_class(@submission, :spring_board), placeholder: 'Spring room/board' %>
            <%= form.number_field :spring_other, :class => field_class(@submission, :spring_other), placeholder: 'Spring other' %>
            <%= form.number_field :spring_hours, :class => field_class(@submission, :spring_hours), placeholder: 'Spring hours' %>
          </div>
        </div>
      </div>
      <div>
        <%= form.label :frequency, 'Is this request for semester or quarter terms?' %>
        <%= form.select :frequency, options_for_select(
          [
            ['Semesterly terms', 'semester'],
            ['Quarterly terms', 'quarter']
          ],
          @submission.frequency
        ) %>
      </div>
      <div>
        <p class="<%= field_class(@submission, :expense) %>">Adobe PDF of the institution's expense page(s) from the current school catalog:</p>
        <%= form.file_field :expense %>
        <% if @submission.expense.present? %>
          <%= link_to 'View expense page(s)', @submission.expense.url %>
        <% end %>
      </div>
    </div>
    <div class="not-required-on-reapply">
      <div class="motivation">
        <h2>Motivation, commitment, and goals</h2>
        <div>
          <%= form.text_area :motivation, :class => field_class(@submission, :motivation), placeholder: 'Provide reasons for choosing this profession, motivation to pursue this degree, commitment to work with children and future goals.' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/submissions/_honors.html.erb
<div>
  <%= form.add_nested_fields_link :honors, 'Add honor' %>
  <%= form.nested_fields_for :honors do |honor| %>
    <div>
      <%= honor.text_field :name, placeholder: 'Name' %>
    </div>
  <% end %>
</div>

app/views/submissions/_institutions.html.erb
<div>
  <%= form.add_nested_fields_link :institutions, 'Add college or university' %>
  <%= form.nested_fields_for :institutions do |institution| %>
    <div>
      <%= institution.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
      <%= institution.text_field :degree, placeholder: 'Degree received' %>
    </div>
    <div>
      <%= institution.text_field :gpa, placeholder: 'GPA' %>
    </div>
    <div>
      <%= institution.label :start, 'From date:' %>
      <%= institution.number_field :institution_start_month, :placeholder => 'Starting month', :required => true %>
      <%= institution.number_field :institution_start_year, :placeholder => 'Starting year', :required => true %>
    </div>
    <div>
      <%= institution.label :end, 'To date:' %>
      <%= institution.number_field :institution_end_month, :placeholder => 'Ending month', :required => true %>
      <%= institution.number_field :institution_end_year, :placeholder => 'Ending year', :required => true %>
    </div>
  <% end %>
</div>

app/views/submissions/_relative.html.erb
<div>
  <%= form.nested_fields_for :relatives do |relative| %>
    <div>
      <div>
        <%= relative.text_field :name, :class => field_class(@submission, :permanent_address), placeholder: 'Name' %>
      </div>
      <div>
        <%= relative.text_field :relationship, :class => field_class(@submission, :permanent_address), placeholder: 'Relationship' %>
      </div>
    </div>
    <div>
      <div>
        <%= relative.text_field :address, :class => field_class(@submission, :permanent_address), placeholder: 'Address' %>
      </div>
      <div>
        <%= relative.text_field :city, :class => field_class(@submission, :permanent_address), placeholder: 'City' %>
      </div>
      <div>
        <%= relative.text_field :state, :class => field_class(@submission, :permanent_address), placeholder: 'State' %>
      </div>
      <div>
        <%= relative.number_field :zip, :class => field_class(@submission, :permanent_address), placeholder: 'Zip' %>
      </div>
    </div>
  <% end %>
</div>

app/views/submissions/_volunteers.html.erb
<div>
  <%= form.add_nested_fields_link :volunteers, 'Add volunteerism' %>
  <%= form.nested_fields_for :volunteers do |volunteer| %>
    <div>
      <%= volunteer.text_field :name, placeholder: 'Name' %>
    </div>
  <% end %>
</div>

app/views/submissions/edit.html.erb
<div class="main">
  <h1>Edit Scholarship Application</h1>

  <div class="submissions">
    <div class="submission-form">
      <%= render 'form', submission: @submission %>
    </div>
  </div>
</div>

app/views/submissions/index.html.erb
<div class="main">
  <h1>Applicant Submissions</h1>

  <div class="submissions">
    <p id="notice"><%= notice %></p>

    <p>Below is the list of applicant submissions that have been marked as complete by NAJA.</p>

    <p>Please select each one to complete the committee grading.</p>

    <table>
      <thead>
        <tr>
          <th>Applicant</th>
          <th>Submission</th>
          <th>Transcripts</th>
          <th>Recommendations</th>
          <th>Score</th>
          <th>Overall</th>
        </tr>
      </thead>
      <tbody>
        <% @submissions.each do |submission| %>
          <tr>
            <td><%= link_to name(submission), new_evaluation_path(:submission => submission) %></td>
            <td>
              <table class="no-bottom-border">
                <tr><td><%= link_to 'Submission', submission %></td></tr>
                <% s = previous_submission(submission) %>
                <% if s %>
                  <tr><td><%= link_to 'Previous submission', submission_path(s) %></td></tr>
                <% end %>
              </table>
            </td>
            <td>
              <table class="no-bottom-border">
                <% submission.institutions.each do |institution| %>
                  <% if institution.transcript %>
                    <tr><td><%= link_to institution.name, institution.transcript.upload.url %></td></tr>
                  <% end %>
                <% end %>
                <% if s %>
                  <tr><td>Previous transcript(s):</tr></td>
                  <% s.institutions.each do |institution| %>
                    <% if institution.transcript %>
                      <tr><td><%= link_to institution.name, institution.transcript.upload.url %></td></tr>
                    <% end %>
                  <% end %>
                <% end %>
              </table>
            </td>
            <td>
              <table class="no-bottom-border">
                <% submission.recommendations.each do |recommendation| %>
                  <tr><td><%= link_to recommendation.name, recommendation %></td></tr>
                <% end %>
                <% if s %>
                  <tr><td>Previous recommendation(s):</td></tr>
                  <% s.recommendations.each do |recommendation| %>
                    <tr><td><%= link_to recommendation.name, recommendation %></td></tr>
                  <% end %>
                <% end %>
              </table>
            </td>
            <td><%= submission.score(current_user) %> / 20</td>
            <td><%= submission.overall %> / 20</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/submissions/new.html.erb
<div class="main">
  <h1>Scholarship Application</h1>

  <div class="submissions">
    <%= render 'form', submission: @submission %>
  </div>
</div>

app/views/submissions/show.html.erb
<div class="main">
  <h1>Show Applicant Submission</h1>

  <div class="submissions">
    <p id="notice"><%= notice %></p>

    <p>Please note that any changes made to this form will not be saved.</p>

    <div class="submission-form">
      <%= render 'form-disabled', submission: @submission %>
    </div>
  </div>
</div>